server:
  port: 8083
spring:
  application:
    name: printService
  cloud:
    stream:
      bindings:
        input:
          destination: printMessage
          content-type: application/json
          binder: local_rabbit
          group: printService
      binders:
          local_rabbit:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
